- .gitattributes
git changes line endings for ttf files
see http://stackoverflow.com/questions/1967370/git-replacing-lf-with-crlf
> style(.gitattributes): switch off git line endings checking for ttf

- src/input/input.css
карточка https://trello.com/c/YR7jICg2/212-input-textarea-min-width-size
выключил min-width у input c width='available'
> fix(input): fix input min-width with width='available' prop

- docs/calendar/README.md
- src/calendar-input/calendar-input.jsx
- src/calendar/calendar-test.jsx
- src/calendar/calendar.jsx
Blur event on input come before calendar focus, and calendar-input fire blur event.
> fix(calendar-input)

- package.json
- src/sidebar/sidebar.css
- src/sidebar/sidebar.jsx
Анимируем sidebar через csstransitiongroup
> feat(*): sidebar csstansitiongroup animation

- package.json
Обновление react-textarea-autosize пакета
Либа была сломана для серверного рендеринга
> feat(*): fix react-textarea-autosize version

- src/input/input.css
- src/select/select.css
- src/textarea/textarea.css
Фикс проблемы с переполнением контентом и растягиванием ширины полей.
> fix(*): fix inner element width overflow in input, select, textarea

- styleguide-fantasy.config.js
> docs(*): minor fix for fantasy demo

- src/calendar-input/fantasy/calendar-input.css
- src/calendar-input/fantasy/index.js
- src/calendar/fantasy/calendar.css
- src/calendar/fantasy/index.js
- src/calendar/index.js
- src/input/fantasy/input.css
Добавлен `CalendarInput` с обновлённым дизайном.
> feat(fantasy): add calendar-input

- package-lock.json
- src/label/README.md
- src/label/fantasy/index.js
- src/label/fantasy/label.css
- src/menu/README.md
- src/popup/README.md
- yarn.lock
Добавлен компонент `Label` из обновлённого дизайна.
> feat(fantasy): add label

- src/input-autocomplete/fantasy/index.js
- src/input-autocomplete/fantasy/input-autocomplete.css
- src/input/fantasy/input.css
- yarn.lock
Добавлен компонент `InputAutocomplete` из обновлённого дизайна.
> feat(fantasy): add input-autocomplete

- src/money-input/fantasy/index.js
Добавлена поддержка компонента MoneyInput для обновлённого дизайна.
> feat(fantasy): add money-input

- src/input/fantasy/input.css
Исправление стилей для неактивных контролов после дизайн-ревью.
> fix(fantasy): change disabled input border style

- docs/select/README.md
- karma.config.js
- src/button/fantasy/button.css
- src/calendar-input/calendar-input-test.jsx
- src/calendar-input/calendar-input.css
- src/calendar-input/calendar-input.jsx
- src/calendar-input/fantasy/calendar-input.css
- src/icon/fantasy/index.js
- src/input/fantasy/input.css
- src/input/fantasy/input_theme_alfa-on-color.css
- src/input/fantasy/input_theme_alfa-on-white.css
- src/menu-item/README.md
- src/menu/fantasy/menu.css
- src/polyfills.js
- src/select/fantasy/index.js
- src/select/fantasy/select.css
- src/select/fantasy/select_theme_alfa-on-color.css
- src/select/fantasy/select_theme_alfa-on-white.css
- src/select/select-test.jsx
- src/select/select.jsx
- src/select/select_theme_alfa-on-color.css
- src/select/select_theme_alfa-on-white.css
- yarn.lock
Добавлен компонент `Select` из обновлённого дизайна.
> feat(fantasy): add select

- arui-demo/components/styleguide/demo-styles.css
- src/textarea/fantasy/textarea.css
- src/textarea/fantasy/textarea_theme_alfa-on-color.css
- src/textarea/fantasy/textarea_theme_alfa-on-white.css
- src/textarea/textarea.jsx
Исправления стилей `top` элемента в `Textarea` для консистентности с `Input` и другими контролами.
> fix(fantasy): fix textarea top color

- src/checkbox-group/checkbox-group.css
- src/radio-group/radio-group.css
Если использовать компонент атамарно, например, как в наших новых демках. Отсутсвует корректный шрифт для ошибки.
> fix(*): add missed font for checkbox and radio group

- src/inline-submit-button/fantasy/inline-submit-button.jsx
- src/tag-button/fantasy/tag-button.jsx
Потому, что по-сути декоратор передекорирует, то что итак уже задекорировано.
> fix(*): remove useless perfomance decorators

- src/paragraph/fantasy/index.js
- src/paragraph/fantasy/paragraph.css
Добавляю параграф. Уже нужен в Blueprint-е.
> feat(*): add paragraph in fantasy styles

- arui-demo/components/styleguide/demo-styles.css
- src/menu/README.md
Исправление стилей стайлгайда после сегодняшнего апдейта.
> docs(styleguide): fix row styles

- arui-demo/components/styleguide/demo-styles.css
- src/input/fantasy/input.css
- src/input/fantasy/input_theme_alfa-on-color.css
- src/input/fantasy/input_theme_alfa-on-white.css
- src/select/fantasy/select_theme_alfa-on-color.css
- src/select/fantasy/select_theme_alfa-on-white.css
- src/textarea/fantasy/textarea_theme_alfa-on-color.css
- src/textarea/fantasy/textarea_theme_alfa-on-white.css
- src/vars/fantasy/color-theme_alfa-on-white.css
Нормализация стилей между контролами из обновлённого дизайна.
> fix(fantasy): normalize top & sub styles in controls

- src/attach/fantasy/attach.css
- src/button/fantasy/button.css
- src/calendar-input/fantasy/calendar-input.css
- src/calendar/fantasy/calendar.css
- src/heading/fantasy/heading.css
- src/inline-submit-button/fantasy/inline-submit-button.css
- src/input/fantasy/input.css
- src/label/fantasy/label.css
- src/link/fantasy/link.css
- src/menu-item/fantasy/menu-item.css
- src/menu/fantasy/menu.css
- src/paragraph/fantasy/paragraph.css
- src/popup/fantasy/popup.css
- src/select/fantasy/select.css
- src/tag-button/fantasy/tag-button.css
- src/textarea/fantasy/textarea.css
Инжектинг `box-sizing` в каждый компонент. Для случаев когда не используется `main-fantasy.css`.
> fix(fantasy): add box-sizing border-box to each component

- src/amount/fantasy/amount.css
- src/amount/fantasy/index.js
Добавлен компонент `Amount` из обновлённого дизайна.
> feat(fantasy): add amount

- src/card-input/fantasy/index.js
- src/email-input/fantasy/index.js
- src/phone-input/fantasy/index.js
Добавлены n компонентов `*-input` из обновлённого дизайна.
> feat(fantasy): add card-input, email-input, phone-input

- src/spin/fantasy/index.js
- src/spin/fantasy/spin.css
Добавление компонента `Spin` из обновлённого дизайна.
> feat(fantasy): add spin

- src/input-group/fantasy/index.js
- src/input-group/fantasy/input-group.css
- src/input-group/fantasy/input-group_theme_alfa-on-white.css
- src/vars-fantasy.css
Добавление компонента `InputGroup` из обновлённого дизайна.
> feat(fantasy): add input-group

- src/collapse/README.md
- src/collapse/fantasy/collapse.css
- src/collapse/fantasy/index.js
- src/paragraph/fantasy/paragraph.css
Добавление компонента `Collapse` из обновлённого дизайна. 
Обновил стили отступов в `Paragraph` для предотвращения margin collapsing с родительскими элементами.
> feat(fantasy): add collapse

- src/button/button_theme_alfa-on-color.css
- src/button/button_theme_alfa-on-white.css
- src/button/fantasy/button_theme_alfa-on-color.css
- src/button/fantasy/button_theme_alfa-on-white.css
- src/checkbox-group/fantasy/checkbox-group.css
- src/checkbox-group/fantasy/index.js
- src/checkbox/checkbox.jsx
- src/checkbox/fantasy/checkbox.css
- src/checkbox/fantasy/checkbox_theme_alfa-on-color.css
- src/checkbox/fantasy/checkbox_theme_alfa-on-white.css
- src/checkbox/fantasy/index.js
Добавление компонентов `Checkbox` и `CheckboxGroup` из обновлённого дизайна.
> feat(fantasy): add checkbox & checkbox-group

- src/attach/attach.css
- src/attach/fantasy/attach.css
Текст с именем файла всегда наследовал настройки шрифта из вне.
> fix(attach): add missed font properties

- src/textarea/fantasy/textarea_theme_alfa-on-color.css
- src/textarea/fantasy/textarea_theme_alfa-on-white.css
Исправление стилей неактивного `Textarea`.
> fix(fantasy): fix textarea disabled border style

- src/checkbox/fantasy/checkbox.css
Микрофикс неизвестной переменной в стилях `Checkbox`.
> fix(fantasy): fix checkbox vars in styles

- src/radio-group/README.md
- src/radio-group/fantasy/radio-group.css
- src/radio-group/radio-group.css
Исправление стилей ошибок в `RadioGroup` при `width='available'`.
> fix(radio-group): fix error styles

- src/button/fantasy/button.css
Микроапдейт font-weight у дополнительных `Button` в обновлённом дизайне.
> fix(fantasy): change button extra views font-weight from bold to medium

- package-lock.json
- package.json
- yarn.lock
Чистка неиспользуемых напрямую дев зависимостей.
> chore(*): prune dev deps

- src/link/fantasy/link.css
Обновление стилей выбранных ссылок из обновлённого дизайна.
> fix(fantasy): update checked link styles

- src/checkbox-group/README.md
Проблемы с `CheckBoxGroup` нет, проблема — в демо.
> chore(styleguide): fix checkbox-group demo

- src/select/fantasy/select.css
Исправление цвета ошибки для `Select` из обновлённого дизайна.
> fix(fantasy): fix select error styles

- src/input/fantasy/input.css
- src/input/fantasy/input_theme_alfa-on-color.css
- src/input/fantasy/input_theme_alfa-on-white.css
- src/select/fantasy/select.css
- src/select/fantasy/select_theme_alfa-on-color.css
- src/select/fantasy/select_theme_alfa-on-white.css
- src/textarea/fantasy/textarea.css
- src/textarea/fantasy/textarea_theme_alfa-on-color.css
- src/textarea/fantasy/textarea_theme_alfa-on-white.css
Исправление стилей контролов при одновременном неактивном и инвалидном состоянии.
Сейчас не все контролы выглядят одинаково в таких состояниях из-за специфичности селекторов. Может ли быть одновременно два таких состояния? Ответ — да, например когда какое-то поле неактивно из-за того что зависит от ввода в другое поле и при этом происходит сабмит.
> fix(fantasy): fix form controls styles with disabled & invalid simultaneous states

- src/collapse/fantasy/collapse.css
Исправление бага с прилипшей к контенту ссылкой «Подробнее».
> fix(fantasy): fix collapse expanded content margin

- package.json
> chore(*): hot fix for demo. use stable version

- src/tab-item/fantasy/tab-item.css
- yarn.lock
Обновление стилей для компонента `tab-items`
Дизайнеры наконец договорились
> fix(tab-items): fix tab-items styles according to new design

- src/button/button_theme_alfa-on-color.css
- src/button/button_theme_alfa-on-white.css
- src/button/fantasy/button_theme_alfa-on-color.css
- src/button/fantasy/button_theme_alfa-on-white.css
Правки в стилям псевдо-кнопки в фокусе
https://trello.com/c/NUy7LbNe/335-attach-стили-на-фокусе
> fix(button): fix focused style on pseudo button

- docs/menu/README.md
- docs/select/README.md
- src/menu/README.md
- src/menu/fantasy/menu.css
- src/menu/menu.css
- src/menu/menu.jsx
- src/select/select.jsx
> feat(menu): add in-line group titles

- src/select/fantasy/select.css
- src/select/select.css
Крестик слева, заголовок от центра.
> fix(select): mobile header style

- src/notification/notification.jsx
- src/popup/popup.jsx
Фикс автозакрытия попапов на iOS
> fix(*): autoclosing on ios

- src/popup/fantasy/popup.css
- src/popup/popup.css
- src/select/select.jsx
- yarn.lock
Фикс багов в UIWebView:
1) при прокрутке списка не сразу рендерились невидимые ранее элементы;
2) полноэкранный попап для селекта перематывал страницу вверх.
> fix(popup): fix UIWebView popup bugs

- src/menu-item/README.md
- src/menu/README.md
Поменял текст примеров в демке меню.
> docs(*): add demo for menu and menuitem

- arui-demo/components/preview-with-theme-switcher/index.css
- arui-demo/components/styleguide/demo-styles.css
- styleguide.config.js
Текущая демка невлезала в мобильный режиме.
> feat(*): add mobile adaptive demo

- src/calendar-input/README.md
- src/calendar-input/calendar-input.css
- src/calendar-input/calendar-input.jsx
- src/calendar-input/fantasy/calendar-input.css
- src/calendar-input/fantasy/index.js
- src/calendar-input/index.js
- src/popup/fantasy/popup.css
- src/popup/fantasy/popup_theme_alfa-on-color.css
- src/popup/fantasy/popup_theme_alfa-on-white.css
- src/popup/popup.css
- src/popup/popup.jsx
- src/popup/popup_theme_alfa-on-color.css
- src/popup/popup_theme_alfa-on-white.css
В нативном режиме на мобильниках не доступны дополнительные возможности календаря, такие как ограничения по датам. В этих целях по аналогии с Select вводим параметр, позволяющий открывать календарь в полноэкранном попапе.
> feat(calendar-input): full-screen popup mode for calendar-input on mobile

- src/popup/popup.css
Исправление для больших select
Решает проблему с большими селектами, когда количество вариантов превышает максимальную высоту попапа, появляется скроллинг.
> fix(*): fix overflow for select

- src/tabs/fantasy/tabs-test.jsx
- src/tabs/fantasy/tabs.css
- src/tabs/fantasy/tabs.jsx
Добавил табам возможность скроллиться на мобилке
> feat(tabs): add scrollable functionality

- package-lock.json
- package.json
- src/textarea/textarea.jsx
- yarn.lock
Обновление зависимости до актуальной версии.
> feat(textarea): update react-textarea-autosize to latest

- package-lock.json
- package.json
- src/slide-down/slide-down.jsx
- yarn.lock
Чистка неиспользуемых зависимостей.
> chore(*): remove unused dev deps

- src/checkbox/fantasy/checkbox.css
Стили чекбокса в неопределенном состоянии
В fantasy чекбокс в неопределенном состоянии выглядел неправильно
> fix(checkbox): amend indeterminate checkbox's styles in fantasy

- src/attach/attach-test.jsx
- src/attach/attach.jsx
Сообщение
"
https://alfa-laboratory.github.io/arui-feather/styleguide/#attach
прикрепляем файл
открепляем
этот же самый файл снова не прикрепляется
"
fixed
> fix(*): allow to select, remove, and select file again

- karma.config.js
- src/calendar-input/calendar-input-test.jsx
- src/email-input/email-input-test.jsx
- src/radio/radio-test.jsx
- src/select/select-test.jsx
- src/test-utils.js
- src/textarea/textarea-test.jsx
Добавлено тестирование на актуальном iOS стэке.
> test(*): run ios unit tests

- package-lock.json
- package.json
- src/app-content/app-content.jsx
- src/app-menu/app-menu.jsx
- src/app-title/app-title.jsx
- src/copyright/copyright.jsx
- src/error-page/error-page.jsx
- src/footer/footer.jsx
- src/page/page.jsx
- src/support/support.jsx
- src/user/user.jsx
- yarn.lock
Добавление deprecations для app-компонентов.
Эти компоненты в обозримом будущем переедут в `arui-private`.
> feat(*): deprecate complex app components

- src/button/button.jsx
Добавил атрибут formNoValidate для кнопки
Отключает валидацию полей, которые содержат атрибут pattern
> feat(button): added formNoValidate attribute

- src/attach/attach.jsx
Добавил type=button для кнопки удаления аттачей
При попытке удалить файлы сабмитится форма.
> fix(attach): added type property for clear button

- src/select/README.md
Добавил пример сгруппированного селекта в демо
> feat(*): add example for grouped select in demo

- src/form-field/README.md
- src/form-field/form-field.jsx
- src/form/README.md
- src/popup/README.md
Deprecation свойства `label` в `FormField` в предверии удаления старого дизайна.
> feat(form-field): deprecate label property

- src/input/input.jsx
input noValidate --> formNoValidate
У инпута нет такого атрибута.
> fix(input): fixed attribute

- src/slide-down/fantasy/index.js
Добавление стилей для фэнтезийного компонента slide-down.
При импорте фэнтэзийного slide-down'а не добавлялись стилей, из-за чего валилась верстка.
> fix(slide-down): add styles for fantasy slide-down

- AUTHORS.md
> chore(*): update authors

- gemini/progress-bar.gemini.js
- src/progress-bar/fantasy/index.js
- src/progress-bar/fantasy/progress-bar.css
- src/vars/color-theme_alfa-on-white.css
> feat(progress-bar): add progress-bar fantasy styles

- src/select/fantasy/select.css
- yarn.lock
Добавил оверфлов для нативного слекта
На мобилках если у селекта длинные опции, появляется горизонтальный скролл.
> fix(select): overflow long options for native select

- .travis.yml
- README.md
- package-lock.json
- package.json
- tools/sauce-connect.sh
Перенос sh скрипта для запуска туннеля до Sauce Labs с моего Gist в `./tools`. Ревизии можно и здесь вести.
> chore(*): move sauce connect to tools

- src/sidebar/sidebar.css
- src/sidebar/sidebar.jsx
- yarn.lock
Фикс скролла в сайтбаре
Была проблема в том что при скролле контента в сайтбаре скролился весь сайт под сайтбаром
https://trello.com/c/WSKaWdSU/366-sidebar-поправить-баг-со-скроллом-контента-под-сайтбаром-на-мобильном-телефоне
> fix(sidebar): fix sidebar scroll

- src/amount/amount.jsx
- src/calendar/calendar.jsx
- src/card-input/card-input.jsx
- src/dropdown/dropdown.jsx
- src/email-input/email-input.jsx
- src/money-input/money-input.jsx
- src/phone-input/phone-input.jsx
- src/popup-container-provider/popup-container-provider.jsx
- src/slide-down/slide-down.jsx
Явный вызов cn()
Нужно для react 16
> chore(*): use cn-decorator without implicit toString

- demo/components/playground-with-share-example-button/index.jsx
- demo/components/preview-frame/index.jsx
Микрофикс для подчистки `@cn` ворнингов.
> chore(*): fix demo cn warnings

- src/sidebar/sidebar.jsx
Исправление ошибки в сохранении текущей позации скролла
Внезапно перестал работать document.body.scrollTop, добавил дополнительный способ проверки положения скролла
> fix(sidebar): fix save position on sidebar

- karma.config.js
- package.json
- styleguide.config.js
- webpack.gemini.config.js
- yarn.lock
Обновление на последних презетов.
> chore(*): update to arui-presets v4

- src/popup/popup-test.jsx
- src/popup/popup.jsx
Удаление неиспользуемого состояния в Popup.
> feat(popup): remove unused hovered state

- karma.config.js
Настройка списка файлов для code coverage.
> test(coverage): tune file list

- package.json
Обновление arui-presets
Фикс для ie10
> chore(*): up arui-presets

- package-lock.json
- package.json
Обновление package-lock.json
package.lock устаревший. Апнул + пришлось обновить lint-staged конфиг
> chore(*): up package lock

- src/notification/notification.css
- src/notification/notification.jsx
- src/swipeable/index.js
- src/swipeable/swipeable-test.jsx
- src/swipeable/swipeable.jsx
Добавлен компонент Swipeable и применен к компоненту Notification
Данный компонент добавляет функционал осуществления каких-либо действий по свайпу.
В данном ПР добавлена возможность закрытия Notification по свайпу вправо, влево или вверх.
https://trello.com/c/9NLJDhXK/321-notification-swipe-support
> feat(swipeable): add swipeable component

- src/input/input-test.jsx
Возвращение назад файла с тестами для Input, случайно удалённого с большими правками в v10.
> test(input): bring back test file content

- src/popup/popup_theme_alfa-on-color.css
- src/popup/popup_theme_alfa-on-white.css
Исправление цветов градиента на актуальные в `<Popup />`.
> fix(popup): fix gradient colors

- src/theme-provider/theme-provider.jsx
Удаление больше неиспользуемой темы после апдейта на v10.
> feat(theme-provider): remove alfa-on-colored from theme prop values

- src/mq/decorator-test.jsx
- src/mq/decorator.jsx
MQ декоратор
Интерфейс mq компонента не очень удобен во многих случаях, это фактически альтернативный интерфейс.
> feat(*): add mq decorator

- demo/components/styleguide/index.jsx
Добавление полифиллов для корректной работы стайлгайда.
> docs(styleguide): add polyfills

- src/swipeable/swipeable-test.jsx
- src/swipeable/swipeable.jsx
Убрал при handleSwipeEnd при unmount'е компонента. Поправил соответствующий тест.
> fix(swipeable): remove handleSwipeEnd on component unmount

- src/progress-bar/progress-bar.jsx
фикс для
https://github.com/alfa-laboratory/arui-feather/issues/346
> fix(*): fix react undefined in progress bar

- package-lock.json
- src/flag-icon/README.md
- src/input-autocomplete/README.md
- src/sidebar/README.md
Исправление демо `<InputAutocomplete />`.
https://github.com/alfa-laboratory/arui-feather/issues/351
> docs(*): fix input-autocomplete demo

- src/dropdown/dropdown.jsx
Add custom target for popup in dropdown
Для того, чтобы попап растянуть на полный экран в мобилках.
> feat(*): add custom target for popup in dropdown

- package-lock.json
- package.json
This is pull request for webpack maintainer which demonstrate that our gemini emits error with webpack 3.4.1 
Do not delete / close it
> chore(*): up to webpack 3.4.1

- src/popup/popup.jsx
Исправление ошибки SSR у `<Popup />` после [11.0.0](https://github.com/alfa-laboratory/arui-feather/releases/tag/v11.0.0).
> fix(popup): fix server-side rendering

- src/flag-icon/flag-icon.css
Продолжаем переходить на `inline-flex` в компонентах. Больше гибкости, простое центрирование по вертикали, etc...
> fix(flag-icon): change root style to inline-flex

- src/intl-phone-input/intl-phone-input.jsx
Фикс сдвига `<Popup />` относительно `<SelectButton />`. Design-only.
> fix(intl-phone-input): fix popup offset values

- package-lock.json
- package.json
- src/popup/popup.jsx
- src/render-in-container/render-in-container-test.jsx
- src/render-in-container/render-in-container.jsx
Добавление возможности использования текущих версий библиотек проектам с React 15.
> feat(*): support react 15

- package-lock.json
- package.json
- src/render-in-container/render-in-container.jsx
Использование deprecations в более тихом формате, не на каждый рендер.
> fix(render-in-container): use less loud deprecation warnings

- src/popup/popup.css
- src/popup/popup.jsx
- src/popup/popup_theme_alfa-on-color.css
- src/popup/popup_theme_alfa-on-white.css
Добавление верхнего градиента в Popup (был только нижний).
Появляется при скролле для постепенного затемнения у верхней границы. 
Вместо getScrollbarWidth использован clientWidth (чтобы градиент не перекрывал скроллбар).
> feat(popup): add gradient on top while scrolling

- package-lock.json
- package.json
- yarn.lock
> fix(package): update libphonenumber-js to the latest

- package-lock.json
- package.json
- yarn.lock
> Greenkeeper/es6 promise 4.2.2

- src/button/button.css
> fix(button): fix button alignment

- src/resize-sensor/resize-sensor.jsx
Иногда стреляет при других ошибках, хочется видеть более чистый лог.
> refactor(resize-sensor): add extra checks for listeners

- src/input/input.css
- src/input/input_theme_alfa-on-color.css
- src/input/input_theme_alfa-on-white.css
Небольшие фиксы стилей для автофилла.
Взяты отсюда:
https://github.com/alfa-laboratory/arui-feather/pull/408
> fix(input): fix autofill styling

- src/slide-down/slide-down-test.jsx
- src/slide-down/slide-down.jsx
Добавление коллбэков анимации для Slidedown
Хотелось бы уметь понимать, когда компонент начинает и заканчивает анимироваться
> feat(slidedown): added animation callbacks

- .travis.yml
https://github.com/travis-ci/travis-ci/issues/8836
> chore(*): fix headless chrome on travis

- src/popup/calc-drawing-params.js
Поправил ошибку в демо.
Fix issue https://github.com/alfa-laboratory/arui-feather/issues/469
> refactor(popup): pass popup.offset.fitContainer directly to calcFitContainerFactor to avoid incorrect mangling by UglifyES

- README.md
- src/calendar/images/2_arrow_cl.svg
- src/calendar/images/2_arrow_cr.svg
- src/calendar/images/2_arrow_wl.svg
- src/calendar/images/2_arrow_wr.svg
- src/calendar/images/arrow_cl.svg
- src/calendar/images/arrow_cr.svg
- src/calendar/images/arrow_wl.svg
- src/calendar/images/arrow_wr.svg
> docs(*): update copyright years & naming

- src/checkbox/checkbox.css
> fix(checkbox): stop checkbox shrinking

- demo/template.html
- package-lock.json
Включение аналитики в демо. Лучше поздно, чем никогда :)
> chore(*): add google analytics to demo

- package-lock.json
- package.json
- yarn.lock
> Greenkeeper/sinon 4.2.1

- package-lock.json
- package.json
- yarn.lock
> Greenkeeper/sinon 4.3.0

- package-lock.json
- package.json
- yarn.lock
> Greenkeeper/mocha 5.0.1

- .travis.yml
- package-lock.json
- package.json
- src/intl-phone-input/intl-phone-input.jsx
- yarn.lock
> Greenkeeper/libphonenumber js 1.0.24

- package-lock.json
- package.json
Пока greenkeeper не отработал хук, вручную подымем.
> chore(*): update arui-presets to 4.11.10

- README.md
Добавление вакансии в команду дизайн-системы.
https://hr.alfabank.ru/vacancies/ui-dev
> docs(readme): add vacancy section

- src/intl-phone-input/intl-phone-input-test.jsx
- src/intl-phone-input/intl-phone-input.jsx
Доработано форматирование телефонного номера при вводе. 
Теперь телефонный номер вводится согласно маске страны. 
Теперь нельзя ввести телефонный номер длиннее чем маска.
> fix(intlPhoneInput): fixed formatting of phone on input

- src/input/README.md
- src/select/README.md
- src/select/select.jsx
Добавлена возможность пробрасывать пропсы для menu Item в компоненте select
Это позволит сейчас делать некоторые элемента спсика недоступными для выбора, пробрассывать доп классы и тд
> feat(*): add prop option for select control items

- src/intl-phone-input/intl-phone-input.jsx
Фикс проблемы с выбором стран с приоритетами. Например, выбираем в селекте Казахстан, начинаем вводить в поле и страна переключается на Россию. Та же самая проблема с NANP (Канада -> США).
NB: `for ... of` пока нафиг: https://daverupert.com/2017/10/for-of-loops-are-bad/
> fix(intl-phone-input): fix country setting

- src/popup/popup.jsx
Проверка на наличие this.inner для случаев когда его ещё нет.
> fix(popup): check this.inner for gradient style

- package.json
> chore(package): update react-styleguidist to version 6.2.7

- demo/components/preview-with-theme-switcher/index.jsx
- package-lock.json
- package.json
> Greenkeeper/arui presets 4.11.14

- package-lock.json
- package.json
> Greenkeeper/react styleguidist 6.4.0

- src/button/README.md
- src/icon/README.md
- src/spin/README.md
— Обновлённая ссылка на полный список иконок в Icon и незначительные правки в описании Button и Spin.
— Обновление demo.
> docs(*): update examples

- package-lock.json
- package.json
> Greenkeeper/html reporter 2.12.2

- src/calendar-input/calendar-input.jsx
Цифровая клавиатура на мобильных девайсах в CalendarInput
При фокусе на поле инпута выезжает буквенная клавиатура, но по сути пользовтаель может вводить только цифры. Изменения позволят отображать цифровую клаву сразу.
> feat(calendar-input): numeric keyboard

- src/input/input-test.jsx
- src/input/input.jsx
При вызове у компонента input метода focus каретка устанавливается в начале элемента.
Этот пул ставит каретку в конец
> feat(*): set caret to end of input on public focus method call

- src/popup/popup.jsx
- src/select/select.jsx
Добавил prop maxHeight в Popup и Select.
Необходимо ограничить высоту длинного выпадающего списка.
> feat(popup,select): Add maxHeight prop

- package-lock.json
- src/input-autocomplete/input-autocomplete.jsx
Исправление инпута с автокомплитом
Если для инпута указан hint, то попап автокомплита открывается под хинтом, что выглядит не очень аккуратно.
Исправление делает так, чтобы попап открывался сразу под инпутом - то есть также как если бы hint для инпута не был указан.
> fix(input-autocomplete): fix hint on input autocomplete

- .travis.yml
- README.md
Удаление остатков упоминаний о гринкипере
Удаление за ненадобностью, после отключения гринкипера
> chore(*): removing all references about greenkeeper

- .travis.yml
- src/textarea/textarea.css
Добавил фиксы для лэйбла и скролла в **Textarea**
До:
После:
До:
После:
> fix(textarea): fix label and scroll in autosize textarea

- src/input/input.jsx
- src/masked-input/mask.js
- src/masked-input/masked-input.jsx
Использование пробелов в маске для Input-а
Нужна маска в которую я бы мог вводить пробелы. В моем случае маска которая позволит вводить буквы, цифры, нижнее подчеркивание, дефис и пробелы.
> feat(input): useWhitespaces with mask

- .editorconfig
- src/button/README.md
- src/button/button.css
- src/button/button.jsx
- src/button/button_theme_alfa-on-color.css
- src/button/button_theme_alfa-on-white.css
Добавлена кнопка со скруглёнными углами
> Add rounded button

- .travis.yml
Added `deploy` in `travis.yml`
> chore(travis): Deploy on master

- src/select/select.jsx
Продолжение https://github.com/alfa-laboratory/arui-feather/pull/656 из внутренней ветки
> fix(select): fix jumping "table-caption" element in safari

- README.md
Фикс названия параметра для запуска тестов
> fix(*): incorrect param for test run

- src/input-autocomplete/__snapshots__/input-autocomplete.test.jsx.snap
- src/input-autocomplete/input-autocomplete.jsx
- src/input-autocomplete/input-autocomplete.test.jsx
Свойство defaultValue для InputAutocomplete теперь работает (а не просто присутствует в документации).
> fix(input-autocomplete): added default value support

- src/money-input/money-input.css
- src/money-input/money-input.jsx
Component money-input, width: 'available' prop handling fix
> fix(money-input): width available prop and CSS

- src/icon/icon.css
- src/icon/icon.jsx
- tools/icon/utils.js
Отсутствовало значение `xxxl` для пропса `size` компонента Icon.
> fix(icon): fix size prop type

- package.json
- yarn.lock
Обновление library-utils
Для генерации корректных тайпингов нужно обновить library-utils
> chore(*): update library-utils

- src/polyfills.js
Добавил дополнительные полифилы
Необходимо для корректной работы в ie10+. Данные методы использую в проектах команды и приходиться раз за разом переопределять полифилы в каждом проекте
> feat(polyfills): extends polyfills

- src/link/link.jsx
- src/link/link.test.jsx
У ссылки, у которой свойство disabled=true при клике теперь будет вызываться колбэк onDisabledLinkClick, а onClick будет использоваться при условии disabled=false.
> feat(link): add check before click on disabled link

- README.md
1. Привёл контент README в соответствии с [MDLint](https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md).
2. Убрал упоминание [quality-check](https://github.com/alfa-laboratory/arui-feather/issues/798)
Приводим документацию к единому стилю и улучшаем её читабельность.
> docs(*): cleanup README markdown

- package-lock.json
- package.json
- src/grid-col/grid-col.jsx
Исправление проптайпов для grid-col
Функционально эти вариации проптайпов и так поддерживаются, но из-за того, что они не прописаны в проптайпах - их невозможно использовать в ts проектах
> fix(grid-col): valid proptypes

- README.md
https://github.com/alfa-laboratory/arui-feather/issues/771
> docs(*): up node version in readme

- src/notification/notification.css
Исправил поведение Notification компонента в safari 11
Этот PR решает проблему описанную в #642
> fix(notification): fix safari bug visibility

- src/input-autocomplete/__snapshots__/input-autocomplete.test.jsx.snap
- src/input-autocomplete/input-autocomplete.jsx
- src/input-autocomplete/input-autocomplete.test.jsx
- src/menu/menu_theme_alfa-on-color.css
- src/menu/menu_theme_alfa-on-white.css
добавил возможность устанавливать свойства для опций у поля ввода с автокомплитом
> feat(input-autocomplete): add props to input autocomplete options

- src/toggle/README.md
- src/toggle/__snapshots__/toggle.test.jsx.snap
- src/toggle/index.js
- src/toggle/toggle.css
- src/toggle/toggle.jsx
- src/toggle/toggle.test.jsx
> feat(toggle): introducing toggle component

- src/input-autocomplete/README.md
Добавил полнотекстовый поиск в функцию фильтрации для InputAutocomplete
Что это даёт:
* делать опечатки при наборе
* искать по нескольким символам (причём символы могут быть разноудалены друг от друга)
> feat(InputAutocomplete): add full text filtering

- src/input/README.md
- src/money-input/money-input.css
> fix(money-input): fixed styles for MoneyInput view=filled

- src/calendar/calendar.jsx
Добавил поле state в компоненте Calendar
В компоненте имеется обращение к полю state.month, которое там отсутствует.
> fix(calendar): add missing state

- src/input-autocomplete/input-autocomplete.jsx
Добавлена возможность определять класс для контейнера со списком опций.
> feat(input-autocomplete): add className for popup options container

- src/toggle/toggle.css
- src/toggle/toggle.jsx
- src/toggle/toggle.test.jsx
Компоненту Toggle добавлен параметр, которым можно указать положение Лэйбла относительно переключателя - справа или слева, по-умолчанию слева.
> feat(toggle): label position property

- src/radio-group/radio-group.css
Label Компонента RadioGroup теперь переносится на новую строку, при необходимости.
> fix(radio-group): label wrap

- package-lock.json
- package.json
Обновил husky
Обновил хаски и перенёс скрипты в соответствующий раздел, по документации https://github.com/typicode/husky#upgrading-from-014
Issue: https://github.com/alfa-laboratory/arui-feather/issues/888
> feat(*): update husky and remove legacy calls from scripts

- package.json
- src/grid-col/grid-col.jsx
- src/grid-row/grid-row.jsx
- src/swipeable/swipeable.jsx
- src/tab-item/tab-item.jsx
- src/tabs/tabs.jsx
https://github.com/alfa-laboratory/arui-feather/issues/904
> chore(*): remove decorated default exports

- package-lock.json
- package.json
- yarn.lock
Обновил зависимости, которые используют старый API react. См. #913
> chore(deps): update dependencies which use old React API

- src/heading/__snapshots__/heading.test.jsx.snap
- src/heading/heading.css
- src/heading/heading.jsx
Добавлена возможность отключить (обнулить) дефолтный margin.
> feat(heading): prop for default margins

- package-lock.json
- package.json
- src/amount/__snapshots__/amount.test.jsx.snap
- src/amount/amount.jsx
- src/amount/index.js
- src/cn.js
- src/theme-provider/theme-provider.jsx
- styleguide.config.js
https://github.com/alfa-laboratory/arui-feather/pull/920
Начинаю заново, буду делать по пачке компонентов
> chore(*): use bem-cn

- src/attach/__snapshots__/attach.test.jsx.snap
- src/attach/attach.jsx
- src/attach/index.js
> chore(*): use bem-react-classname for attach

- src/checkbox-group/__snapshots__/checkbox-group.test.jsx.snap
- src/checkbox-group/checkbox-group.jsx
- src/checkbox-group/index.js
> chore(*): use bemcn for checboxgroup

- package-lock.json
- package.json
> fix(*): up arui-demo

- package.json
- src/card-input/card-input.jsx
- src/email-input/email-input.jsx
- src/input-autocomplete/input-autocomplete.jsx
- src/money-input/money-input.jsx
- src/phone-input/phone-input.jsx
- src/tab-item/themed.js
Билд в либе сломан.
Добавляем в test сборку чтоб проверять на ci что все ок
> chore(*): fix build library

- src/lib/currency-codes.ts
https://github.com/alfa-laboratory/arui-feather/issues/1022
Поставил входящий тип у `getCurrencySymbol` как ключ объекта `CURRENCY_MAP`.
Вопрос правильно ли это, потому что по коду могло быть, что если ключ не найден, то просто возвращается переданная строка из функции...
> chore(currency-codes): currency-codes to typescript

- src/lib/easings.ts
- src/lib/scroll-to.test.ts
- src/lib/scroll-to.ts
Перевод scroll-to на typescript
https://github.com/alfa-laboratory/arui-feather/issues/1020
> chore(scroll-to): scroll-to to typescript

- src/select/index.ts
- src/select/select.tsx
https://github.com/alfa-laboratory/arui-feather/issues/1031
> fix(*): fix select demo

- src/lib/related-target.test.ts
- src/lib/related-target.ts
https://github.com/alfa-laboratory/arui-feather/issues/1035
> chore(related-target): related-target to ts

- .github/CONTRIBUTING.md
https://github.com/alfa-laboratory/arui-feather/issues/1036
> chore(*): use typescript in contribution examples

- package-lock.json
- package.json
Чинит Col width={2}
https://github.com/alfa-laboratory/bem-react-classname/pull/7
> fix(*): up bemreact classname

- jest.config.js
https://github.com/alfa-laboratory/arui-feather/issues/1045
> test(coverage): update files ignore pattern

- src/money-input/money-input.tsx
> fix(*): money input optional props

- src/masked-input/masked-input.test.tsx
- src/masked-input/masked-input.tsx
Фикс установки новой маски для маскированного инпута.
Поправил вызов setMask который обновлял маску без учёта useWhitespaces, что не позволяло после обновления использовать маску с пробелами.
> fix(masked-input): fixed setMask call when changing mask

- .travis.yml
- README.md
- appveyor.yml
https://github.com/alfa-laboratory/arui-feather/issues/1047
> chore(*): up node version

- src/attach/attach.test.tsx
- src/attach/attach.tsx
* Исправлены модификаторы доступа для ссылок на private
* Удалены неиспользуемые ссылки
* Добавлены отсутствующие типы
https://github.com/alfa-laboratory/arui-feather/issues/1061
> feat(attach): Change Attach.tsx refs prorerty visibility to private

- src/collapse/collapse.test.tsx
- src/collapse/collapse.tsx
https://github.com/alfa-laboratory/arui-feather/issues/1074
Поставил инстансу тип any, может у кого-то есть идея получше...
> feat(collapse): update visibility modifiers

- src/test-utils.ts
Добавляет типы
Добавляет типы в файл test-utils.ts
исправляет https://github.com/alfa-laboratory/arui-feather/issues/1065
> fix(test-utils): adds types

- src/input/input.test.tsx
Closes #1016
вернул в строй закомментированный тест
> test(input): uncomment test

- src/performance.js
> refactor(performance): add deprecated to perfomance decorator

- src/input-autocomplete/input-autocomplete.tsx
Добавил отсутствующий *data-test-id* атрибут
в props был указан - в компонент не пробрасывался
> fix(data-test-id): fix small old mistake - added data-test-id

- src/plate/plate.css
- src/plate/plate.tsx
Добавляет новое состояние для компонента, а именно `prop` отвечающий за `background-color` и `border-color`
Ссылка на макет
https://www.figma.com/file/NDAzQX1HYAJ2NtQQHNo4LDLs/NIB-Components?node-id=38%3A22
> feat(plate): adds new prop "warning" for type

- src/money-input/money-input.tsx
Исправление типизации в рамках https://github.com/alfa-laboratory/arui-feather/issues/1124
> fix(money-input): change props type

- src/intl-phone-input/intl-phone-input.test.tsx
- src/intl-phone-input/intl-phone-input.tsx
> fix(intl-phone-input): format value on mount

- src/calendar-input/utils.ts
- src/calendar/calendar.tsx
- src/calendar/utils.ts
- src/grid-col/grid-col.tsx
- src/grid-row/grid-row.tsx
- src/input/input.tsx
- src/masked-input/mask.ts
- src/masked-input/masked-input.tsx
- src/menu/menu.tsx
- src/performance.js
- src/popup/popup.tsx
- src/select/select.tsx
Немного прибрался https://github.com/alfa-laboratory/arui-feather/issues/1125
> refactor(*): remove unnecessary types from jsdoc

- src/phone-input/phone-input.test.tsx
- src/phone-input/phone-input.tsx
Добавлен дополнительный обработчик для значения ввода телефона
https://github.com/alfa-laboratory/arui-feather/issues/1113
> Add extra handler for phone-input to format value (#1113)

- src/input/input.tsx
Продублировала дефолтные пропсы из defaultProps в JSDoc описание пропсов
https://github.com/alfa-laboratory/arui-feather/issues/1155
> chore(input): add default value in JSDoc

- src/vars.css
Такой вот реквест.
По просьбе дизайнеров обновил максимальную ширину контента 1094 → 1092.
> feat(*): updated content max width

- .travis.yml
Добавляет `npm run compile` для тестирования изменений
Закрывает [issue](https://github.com/alfa-laboratory/arui-feather/issues/1161)
> fix(travis): adds compile command for unit "scope"

- jest.config.js
Меняет расширение для файла.
Без этих изменений ломаются тесты.
> fix(jest.config): change extension mocking file for modules

- src/textarea/README.md
- src/textarea/textarea.css
- src/textarea/textarea.test.tsx
- src/textarea/textarea.tsx
Добавлена иконка в Textarea
См. также #1177
> feat(textarea): add icon in textarea

- src/radio/radio.css
Корректный отступ у Radio кнопки
Если не задать text у радио кнопки - будет лишний отступ, и в некоторых случаях из-за отступа отображается с артефактом
> fix(radio): replace margin-right from box to text margin-left

- package-lock.json
> fix(*): adds lock file

- src/money-input/money-input.css
money input c пропсой width available растягивается на всю ширину
Активное поле слева от линии должно растягиваться на всю ширину
> fix(*): money input width available

- package-lock.json
> fix(*): updated package-lock

- src/input/index.ts
- src/input/input.tsx
- src/input/input_theme_alfa-dark.css
- src/input/input_theme_alfa-light.css
Добавление двух новых тем в компонент Input с использованием обновленной палитры цветов.
> feat(client): add new themes for input component

- package-lock.json
- package.json
- src/button/button_theme_alfa-dark.css
- src/button/button_theme_alfa-light.css
- src/button/index.ts
Добавление двух новых тем в компонент Button с использованием обновленной палитры цветов.
> feat(*): add new themes for button

- .github/workflows/npm-publish.yml
Прави план для создания библиотеки
С этими изменеиями версия для установки зависимостей, что в тесте, что при создании либы будет одинакова.
> fix(npm-publish): add getting same node version as in tests action

- src/input/input_theme_alfa-dark.css
- src/input/input_theme_alfa-light.css
Исправление импорта переменных в файлах с темами и добавление перекрытия стандартных стилей компонента.
> feat(client): fix import and hover for input theme

- src/tab-item/tab-item.css
- src/tabs/tabs.css
Добавление двух новых тем в компоненты Tabs и TabItem с использованием обновленной палитры цветов.
> feat(client): add new theme for tabs and tab-item

- package-lock.json
- package.json
- src/label/label.css
- src/notification/notification.css
- src/notification/notification.tsx
Добавление двух новых тем в компоненты Notification и Label с использованием обновленной палитры цветов
> feat(*): add new themes for label and notification

- src/heading/heading.css
- src/list/list.css
- src/list/list.tsx
Добавление двух новых тем в компонент List с использованием обновленной палитры цветов
Фикс импорта стилей в компоненте Heading
> feat(*): add new themes for list, fix import styles heading

- src/calendar/calendar.tsx
Пролистывание до выбранного года при открытии списка с годами в календаре
Мотивация описана в #1187
> feat(calendar): add scrolling to selected year when open year select

- src/popup/popup.tsx
Выключение скролла у html если попап открывается в полноэкранном режиме  
Fixes #1104
> fix(popup): remove html scroll in fullscreen popup

- src/sidebar/__snapshots__/sidebar.test.tsx.snap
- src/sidebar/index.ts
- src/sidebar/sidebar.css
- src/sidebar/sidebar.tsx
- src/sidebar/sidebar_theme_alfa-dark.css
- src/sidebar/sidebar_theme_alfa-light.css
- src/sidebar/sidebar_theme_alfa-on-color.css
- src/sidebar/sidebar_theme_alfa-on-white.css
Добавление новых тем для компонента sidebar
> feat(*): add new themes for sidebar

- src/popup/popup.css
- src/popup/popup_theme_alfa-dark.css
- src/popup/popup_theme_alfa-light.css
- src/popup/popup_theme_alfa-on-color.css
- src/popup/popup_theme_alfa-on-white.css
- src/select/select.css
- src/select/select_theme_alfa-dark.css
- src/select/select_theme_alfa-light.css
Исправление отступов в select в старых темах на изначальное значение и рефакторинг рамки в popup.
> fix(client): padding for select and popup border

- src/link/link.css
Изменение цвета ссылок в темной теме
Цвет подчеркивания изменен на более контрастный по согласованию с дизайнером
> fix(link): fix link border color

- src/calendar/calendar_theme_alfa-dark.css
- src/calendar/calendar_theme_alfa-light.css
Изменен цвет фона и текста выделенных дней в темной теме
> fix(calendar): fix selected calendar day style in dark theme

- gemini-utils/ok-icon/index.tsx
- gemini-utils/ok-icon/ok-icon-color.tsx
- gemini-utils/ok-icon/ok-icon.tsx
- gemini/button.gemini.js
- gemini/calendar-input.gemini.js
- gemini/notification.gemini.js
- src/button/button.css
- src/select/select.css
> WIP: fix gemini tests

- src/money-input/money-input.tsx
Правки в Money-input
Есть баг в инпуте если ввести в поле 100000, перевести курсор в начало и стереть 1 и попытаться ввести 2, то курсор перескакивает в конец поля и символ не стирается. Воспроизвeсти можно здесь https://digital.alfabank.ru/components/moneyinput
> fix(money-input): fix bug with multiple zeros

- src/select/select.css
- src/select/select_theme_alfa-on-white.css
Добавил в select border-radius, такой же как в input и textarea. В select_theme_alfa-on-white.css оставил стили касающиеся темизации.
> fix(select-styles): add border-radius to select component

- src/button/button_theme_alfa-dark.css
- src/button/button_theme_alfa-light.css
- src/button/button_theme_alfa-on-color.css
Правки в компонент Button
При смене состояния с disabled на active в Safari и ios не меняется цвет текста кнопки в темах light и dark, пользователю кажется что кнопка до сих пор активна, хотя на нее можно нажать и обработчики отрабатываются.
> fix(button): fixed button text color active/disabled on Safari and iOs

- gemini-utils/ok-icon/ok-icon-color.tsx
- gemini-utils/ok-icon/ok-icon.tsx
- src/attach/attach.tsx
- src/calendar-input/calendar-input.tsx
- src/calendar/calendar.tsx
- src/checkbox/checkbox.tsx
- src/input/input.tsx
- src/menu/menu.tsx
- src/notification/notification.tsx
- src/plate/README.md
- src/plate/plate.tsx
- src/popup-header/popup-header.tsx
- src/select/select.tsx
- src/sidebar/sidebar.tsx
Изменен тип импорта, так как импортируются все иконки
> chore(*): change icons import
