src/lib/scroll-to.js
Возвращение дефолтного значения в 0 — при предустановленном `SCROLL_TO_NORMAL_DURATION` аффектились тесты компонентов со `scrollTo` и не было возможности переопределить значение в 0. Плюс `SCROLL_TO_NORMAL_DURATION` оптимален не для всех случаев — при скроллинге на большие дистанции значение слишком мало.
=> feat(scroll-to): set default duration to 0

src/header/header-test.jsx
Лечение периодических фейлов с этим кейсом. `ResizeSensor` не всегда успевает отрабатывать в заданный таймаут. Новое значение взял из:
https://github.com/alfa-laboratory/arui-feather/blob/master/src/resize-sensor/resize-sensor-test.jsx#L34
=> test(header): fix resizing test

docs/input-autocomplete/README.md, src/input-autocomplete/input-autocomplete.jsx
Поправил дефолтный размер input-autocomplete.
У него был `s`, а у всех остальных `m`.
=> fix(input-autocomplete): default size

docs/popup/README.md, src/calendar-input/calendar-input.jsx, src/input-autocomplete/input-autocomplete.jsx, src/input/input.jsx, src/popup/popup-test.jsx, src/popup/popup.jsx, src/select/select.jsx, src/textarea/textarea.jsx
Добавление в Popup аттрибута `data-for`
При e2e тестировании невозможно найти в DOM попапы, относящиеся к конкретному инпуту тк они рендерятся в `body`
Карточка: https://trello.com/c/5gOyfebl/231--
=> feat(popup): add data-for attr

package.json, yarn.lock
core-decorators обновлена до ^0.18.0.
Исправлена ошибка совместимости с Internet Explorer: https://github.com/jayphelps/core-decorators.js/issues/112
=> chore(*): update core-decorators

package.json, src/popup/popup.jsx, yarn.lock
В core-decorators@0.18.0 декоратор debounce был объявлен устаревшим.
К сожалению, лодэшевский debounce несовместим с autobind (и "родным" лодэшевским bind), поэтому было решено объявить функцию через стрелку.
=> fix(popup): replace deprecated debounce decorator

package.json, yarn.lock
Добавление зависимости от babel-runtime
В `arui-presets` был добавлен плагин `transform-runtime`, который позволяет использовать полифилы из пакета `babel-runtime` вместо того, чтобы инлайнить их в каждом файле.
=> fix(package.json): add babel-runtime dependency

src/calendar-input/calendar-input.jsx
Удаление неиспользуемого prop, забытого при миграции на новый дизайн ошибок.
=> refactor(calendar-input): remove unused prop after migration to new field errors

src/input-autocomplete/input-autocomplete.jsx
Добавлены недостающие проптайпы в InputAutocomplete
Нужно для правильных доков/проптайпов
=> fix(input-autocomplete): add missing proptypes

docs/calendar-input/README.md, src/calendar-input/calendar-input.jsx, src/input/input-test.jsx
Добавление забытых `label` и `hint` свойств в `CalendarInput`.
=> fix(fantasy): add label & hint props to calendar-input

docs/input/README.md, docs/masked-input/README.md, src/input/input-test.jsx, src/input/input.jsx, src/masked-input/masked-input-test.jsx, src/masked-input/masked-input.jsx, src/money-input/money-input.jsx
Починил работу маскирования для компонента `InputAutocomplete`
`InputAutocomplete` получал неправильную ссылку на `HTMLElement` инпута, когда последний рендерился через `MaskedInput`. Это ломало `onBlur` и `onFocus` в `InputAutocomlete`, делая его совершенно беспомощным.
=> fix(input-autocomplete): ability to work with masks

package.json
новая версия arui-presets
в новых пресетах вырезаются кооментарии из импортируемых файлов цсс, теперь не будет некольких блоков с лицензией и комментариев к переменным при импорте
=> fix(package): up presets version

src/checkbox/checkbox.jsx, src/radio/radio.jsx
Запрещаем input[type="checkbox"] и input[type="radio"] распространять события
Проблема:
```
<div>
<div className='column' onClick={(e) => alert('вызываюсь дважды')}>
<CheckBox text='Обычный чекбокс' />
</div>
</div>
```
onClick вызывается 2 раза, потому-что клик по label триггирит клик по input[type="checkbox"].
Получаются 2 события, которые начинают всплывать, и их ловит родитель, собственно, поэтому onClick отрабатывает 2 раза.
как решение запретить input[type="checkbox"] распространять события, он у нас всё равно спрятан за `z-index: -1; opacity: 0;` и кликнуть на него намеренно нельзя
=> fix(*): fix click on checkbox and radio fires twice

src/masked-input/masked-input.jsx
Исправление ошибки перескока каретки в крайнее правое положение при добавлении символа перед последним.
1. `<Input mask={ 'AAAA' } />`;
2. `|____` -> поле пустое (| — каретка);
3. `A|___` -> вводим символ 'A': `prevSelection === 1`, `currentValue.length === 0`;
4. `AB|__` -> вводим символ 'B': `prevSelection === 2`,  `currentValue.length === 1`; 
5. `ABD|_` -> вводим символ 'D': `prevSelection === 3`,  `currentValue.length === 2`;  
6. `AB|D_` -> передвигаем каретку на место пропущенной 'C';
7. `ABCD|` -> вводим символ 'C': `prevSelection === 3`, `currentValue.length === 3`.
Каретка перепрыгивает в конец, хотя ожидаемым результатом является `ABC|D`;
=> fix(masked-input): correct caret control condition

src/slide-down/slide-down.css
Ошибка в том что slide-down разлетался на весь экран а потом схлопывался была из-за того что родитель не имеел четких рамок. wiidth 100% исправило это!
=> fix(slide-down): add width parent element for right behavior

src/calendar-input/calendar-input-test.jsx, src/calendar-input/calendar-input.jsx, src/calendar-input/utils.js
Корректная обработка earlierLimit и laterLimit когда value не попадает в них
> Если earlierLimit установлен на более поздний месяц, то если calendar-input пустой, он показывает изначально текущий месяц, где нельзя ничего выбрать
=> fix(calendar-input): correctly set month when limits given

docs/radio-group/README.md, src/radio-group/radio-group-test.jsx, src/radio-group/radio-group.jsx, src/radio/radio_theme_alfa-on-color.css, src/radio/radio_theme_alfa-on-white.css
Добавил проп `disabled` в `RadioGroup`
`RadioGroup` фактически полностью берет на себя взаимодействие с радиокнопками, через него прокидываются все колбеки, он управляет отображением (`type`), значением (`value`), ошибками и тд для дочерних радиокнопок.
Поэтому кажется очень логичным добавить в него возможность выключать все дочерние радиокнопки, что и было сделано.
А еще это очень удобно при использовании `ReduxForm`
=> feat(radio-group): add disabled attribute

src/input/input.css
Фикс бага с высотой контролов в IE11 на текущем дизайне.
FYI: Завёл задачу про тесты на ie в gemini на ближайшее время.
=> fix(input): fix control height in ie11

src/link/fantasy/link.css
Нормализация цвета между темами для подчеркивания ссылок. Необходимо большей частью для `HeaderMenu`.
=> fix(fantasy): fix link border colors

docs/popup/README.md, docs/select/README.md, src/popup/README.md, src/popup/fantasy/popup.css, src/popup/popup.css, src/popup/popup.jsx, src/select/README.md, src/select/select-test.jsx, src/select/select.jsx
В приложениях возникает потребность использовать селекты со списками, плохо отображающимися на мобильных устройствах в нативном виде.
Опция mobileMenuMode позволяет отключить рендер нативного контрола, что даёт возможность показать список через popup.
=> feat(popup): full-screen popup mode for select on mobile

src/icon/icon.jsx
Починил класснейм у иконок.
Иконкам добавлялся класснейм `icon_undefined`
=> fix(icon): remove icon_undefined class name

src/button/button.css, src/button/fantasy/button.css
Fix mouseover after disabled button
Исправлен баг при котором не срабатывало событие mouseover после того как переводишь курсор мыши с disabled кнопки на любую другую
https://trello.com/c/GZTgThg4/309-checkboxgroup-проблемы-с-mouseover
=> fix(button): fix mouseover after disabled button

docs/popup/README.md, docs/select/README.md, src/popup/README.md, src/popup/fantasy/popup.css, src/popup/fantasy/popup_theme_alfa-on-color.css, src/popup/fantasy/popup_theme_alfa-on-white.css, src/popup/popup-test.jsx, src/popup/popup.css, src/popup/popup.jsx, src/select/README.md, src/select/fantasy/select.css, src/select/select.css, src/select/select.jsx
В режиме mobileMenuMode='popup' стоит предусмотреть возможность отменить операцию выбора. Вдобавок можем показать пользователю поясняющий заголовок.
=> feat(select): add header to fullscreen select

src/input-autocomplete/input-autocomplete-test.jsx, src/input-autocomplete/input-autocomplete.jsx, src/menu/menu-test.jsx, src/menu/menu.jsx
При передаче одинаковых value в InputAutocomplete ломалось отображение в компоненте Menu: 
> Warning: flattenChildren(...): Encountered two children with the same key, `test`. Child keys must be unique; when two children share a key, only the first child will be used.
Подправил компоненты InputAutocomplete и Menu чтобы могли принимать ещё параметр `key`
=> fix(autocomplete-key) transfer keys in input-autocomplete and menu

src/checkbox-group/checkbox-group_theme-alfa-on-white.css, src/checkbox-group/checkbox-group_theme_alfa-on-color.css, src/checkbox-group/fantasy/checkbox-group_theme-alfa-on-white.css, src/checkbox-group/fantasy/checkbox-group_theme_alfa-on-color.css, src/label/fantasy/label.css, src/radio-group/fantasy/radio-group_theme_alfa-on-color.css, src/radio-group/fantasy/radio-group_theme_alfa-on-white.css, src/radio-group/radio-group_theme_alfa-on-color.css, src/radio-group/radio-group_theme_alfa-on-white.css
Возвращен цвет лейблов
При переводе CheckboxGroup и RadioGroup в fantasy style был ошибочно переопределен цвет Label на минорный. Необходимо в Label вернуть правильный цвет, а для заголовков CheckboxGroup и RadioGroup установить минорный цвет непосредственно в этих компонентах.
=> fix(label): fix label colors

src/calendar-input/calendar-input.jsx, src/calendar/calendar-test.jsx, src/calendar/calendar.jsx, yarn.lock
Починил навигацию в календаре с клавиатуры
Были следующие проблемы:
1. Не работала стрелочка вниз на календарь-инпуте
2. Не стрелял колбек onMonthChange, если месяц менялся клавиатурными стрелочками
=> fix(calendar): keyboard navigation

docs/input-autocomplete/README.md, src/input-autocomplete/input-autocomplete-test.jsx, src/input-autocomplete/input-autocomplete.jsx
Параметр, для регулирования вызывать ли обновление значения текстового поля при выборе варианта
Текст для подстановки в текстовое поле при выборе варианта
проблему иллюстрирует пример:
начинаем вводить `vko` видим вариант в выпадающем списке, кликаем на него и в инпут подставляется `2`
несколько неожиданно
https://alfa-laboratory.github.io/arui-feather/styleguide/#playground/code=const%20socialNetworks%20=%20%5B%0A%20%20%20%20%7B%20value:%201,%20description:%20'%D0%B2%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82%20facebook',%20text:%20'facebook'%20%20%7D,%0A%20%20%20%20%7B%20value:%202,%20description:%20'%D0%B2%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82%20vkontact',%20text:%20'vkontact'%20%20%7D,%0A%20%5D;%0Afunction%20getFilteredOptions(list,%20typedValue)%20%7B%0A%20%20%20%20if%20(!typedValue)%20%7B%0A% …
=> feat(*): custom text onChange when item selected

arui-demo/template.html, styleguide-fantasy.config.js, styleguide.config.js
Кастомный шаблон для стайлгайда с user-scalable=no, чтобы избежать некоторых багов на мобильных устройствах.
=> chore(styleguide): remove scalability for mobile

styleguide-fantasy.config.js, styleguide.config.js
Чтобы можно было через виртуалку пробрасывать. Кажется, баг со стороны вебпака убрали.
=> chore(*): disable host checking for styleguide

src/calendar-input/calendar-input.jsx
Исправлен баг, позволявший тапнуть дизейбленный контрол.
=> fix(calendar-input): fix clickable disabled calendar-input in mobile popup mode

src/link/fantasy/link.css, src/link/link.css, src/tab-item/fantasy/tab-item.css, src/tab-item/fantasy/tab-item.jsx
Навешиваем стили на link для hover/focus состояние через js.
Состояние focused не всегда пропадает с элемента, даже когда он его вроде как теряет. С css такой проблемы нет. Навешивание классов пока оставил, на случай если кто-то завязался на него в своих проектах
=> fix(link): set hover/focus styles with css instead of js

src/button/button.css, src/input/fantasy/input.css, src/textarea/fantasy/textarea.css, yarn.lock
Избавился от нестед-css в псевдоклассе :not()
6-й пост-css компилит такое:
```
&_has-label:not(&_invalid)
```
в такое
```
.input_has-label:not(&_invalid)
```
В результате у нас не работали инпуты с лейблами.
=> feat(*): negotiation pseudoclasses

src/radio-group/radio-group-test.jsx, src/radio-group/radio-group.jsx
Фикс вызова хендлера onChange когда value у RadioGroup меняется извне через props
Проблема:
Выберем один из радио в радио группе, сбросим value в радио группе, повторно выбрать предыдущий радио - нельзя, только какой-нибудь другой
[пример](https://alfa-laboratory.github.io/arui-feather/styleguide/#playground/code=const%20radios%20=%20%5B%7B%0A%20%20text:%20'one',%0A%20%20value:%201%0A%7D,%20%7B%0A%20%20text:%20'two',%0A%20%20value:%202%0A%7D,%20%7B%0A%20%20text:%20'three',%0A%20%20value:%203%0A%7D,%20%7B%0A%20%20text:%20'four',%0A%20%20value:%204%0A%7D%5D;%0A%0AinitialState%20=%20%7B%0A%20%20%20%20radioGroupValue:%20null%0A%7D;%0A%0A%3Cdiv%3E%0A%20%20%3CRadioGroup%0A%20%20%20%20type='button'%0A%20%20%20%20value=%7B%20state.radioGroupValue%20%7D%0A%20%20%20%20onChange=%7B%20(value)%20=%3E%2 …
=> fix(*): fix repeated click on the same radio after value in radio group was reseted

src/input/fantasy/input.css, src/input/fantasy/input_theme_alfa-on-color.css, src/input/fantasy/input_theme_alfa-on-white.css, src/textarea/fantasy/textarea.css, src/textarea/fantasy/textarea_theme_alfa-on-color.css, src/textarea/fantasy/textarea_theme_alfa-on-white.css
Поправил стили для лейблов внутри невалидных инпутов
Инпуты с ошибкой бессмысленно выкидывали наверх свои лейблы. Это и поправил.
Было:
Стало:
=> fix(input): fix invalid input label styles

src/input-autocomplete/input-autocomplete.jsx
Запрет браузерного автокомплита для `InputAutocomplete`.
=> fix(input-autocomplete): turn off autocomplete

package-lock.json, src/link/link-test.jsx, src/link/link.jsx
Смена тега и удаление лишних атрибутов для заблокированной ссылки
Эти изменения делают ссылку действительно задизейбленной, на данный момент на нее только вешается только класс disabled, но переход по ссылке никак не блокируется
=> feat(link): change tag for disabled link

src/input/fantasy/input.css
Починил стили для дизейбленного инпута без текста, но с лейблом и плейсхолдером.
Было:
=> fix(input): label styles for disabled input

src/radio-group/README.md, src/radio-group/fantasy/radio-group.css, src/radio-group/fantasy/radio-group_theme_alfa-on-color.css, src/radio-group/fantasy/radio-group_theme_alfa-on-white.css, src/radio-group/radio-group-test.jsx, src/radio-group/radio-group.jsx
Добавил свойство `hint` для компонента `RadioGroup` по аналогии с таким же свойством в компоненте Input
В проекте alfaform-dc-ui нужны радиогруппы с подсказками.
=> feat(*): add `hint` prop for radio-group

src/select/select-test.jsx, src/select/select.jsx
Сейчас в компоненте Select с типом `radio` не добавляется класс `checked` в случае выбора
=> feat(*): add `checked` className for radio Select

src/sidebar/sidebar.css
Указание величин без единиц измерения не работает в новой версии Postcss
=> fix(sidebar-closer): fix css rules for sidebar__closer

src/popup/popup.jsx, src/select/select.jsx
Фикс поломки Popup в Select при переходе/ресайзе из мобайла в десктоп.
```
warning.js:35 Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the Popup component.
```
```
Uncaught Error: Cannot show popup without target or position
at Popup.redraw
at Popup.componentWillReceiveProps
```
=> fix(select): fix popup breaking on window resize

src/calendar-input/calendar-input.jsx, src/calendar-input/fantasy/calendar-input.css, src/textarea/fantasy/textarea_theme_alfa-on-color.css, src/textarea/fantasy/textarea_theme_alfa-on-white.css
Фикс цвета полей ввода при `:disabled` атрибуте на контроле. Пример на iOS Safari с нативным `CalendarInput`.
=> fix(*): fix disabled control color in calendar-input & textarea

src/input/input.jsx
Починил setSelectionRange для инпута с маской (он не работал).
=> fix(input): properly select range when mask is set

package-lock.json, src/lib/match-media-test.js, src/lib/match-media.js, src/mq/mq.jsx
Вынес утильные функции mq в отдельный файл
1. так можно их протестить
2. Так можно использовать их вне `Mq`
=> fix(mq): move match media utils functions to lib

package-lock.json, src/form-field/fantasy/form-field.css, src/form-field/form-field-test.jsx, src/form-field/form-field.css, src/form-field/form-field.jsx
Удаление устаревших props в `<FormField />`: `label` и связанного с ним `view`.
Предполагается взамен использование встроенных в контролы форм лейблов:
```
<Input label='foo' />
<Select label='foo' />
<Textarea label='foo' />
...
```
=> feat(*): remove deprecated props in form-field

src/calendar-input/calendar-input.jsx, src/card-input/card-input.jsx, src/email-input/email-input.jsx, src/input/input.jsx, src/money-input/money-input.jsx, src/phone-input/phone-input.jsx
Удаление устаревшего свойства `noValidate` в `<Input />`. Предполагается использование `formNoValidate` взамен.
=> feat(*): remove deprecated noValidate prop in input

src/cn.js
Изменение списка тем при создании `cn` — избавляет от дополнительного использования `<ThemeProvider theme='alfa-on-white' />` на проектах с обновлённым дизайном. Странная тема `alfa-on-colored` больше не используется, цветные иконки можно использовать через флаг `colored`, как на тёмных, так и на светлых подложках.
=> feat(cn): set alfa-on-white theme as default, remove alfa-on-colored theme

src/select/select.css
Необходимо для центрирования `tick` при разной высоте `<SelectButton />`.
=> fix(select): set height to tick element

src/input/input.css
Фикс для инвалидных полей. Встречается в FF:
=> fix(input): remove default browser box-shadow from invalid input

src/input/input.css, src/select/select.css, src/textarea/textarea.css
Фикс исчезания лейблов инпутов при скроллинге на ios 11
Увы, на issue у меня ссылки нет, т. к. меня еще не добавили в трелло, где эта карточка висит
Есть только кусок переписки
```
artptr [4:19 PM]
@here в ios 11 инпуты с топ-лейблом при прокрутке исчезают из-за того, что на них стоит translate3d
[4:19]
если заменить на translateY, то работает нормально
[4:22]
будет ли регрессия в ios 10, если так сделать?
```
=> fix(*): fix labeled inputs on ios11

src/popup-header/README.md
Добавил 'key' при генерации PopupHeader
При запуске демо на локальной машине, заметил, что в консоль вываливаются предупреждения реакта об отсутствии 'key' в компоненте.
Реакт требует добавления 'key' при создании элементов с помощью итерации.
Решил исправить этот баг.
@teryaew @GREENpoint
=> fix(*): fix missing key prop in PopupHeader

src/sidebar/sidebar.jsx
fix(sidebar): fix hidden scrollbar
При открытии сайдбара на body вешается overflow: hidden, из за этого исчезает скроллбар и body смещается вправо на ширину скроллбара, этот ПР испраляет данный баг
=> fix(sidebar): fix hidden scrollbar

src/swipeable/swipeable-test.jsx, src/swipeable/swipeable.jsx
Исправлен баг, когда onSwipe вызывалась по клику на swipeable элемент.
Проблема заключалась в том, что раньше расчет deltaX и deltaY происходил только на mousemove и touchmove эвенты. При клике же мув эвента не вызывается. Поэтому расчет deltaX и deltaY был перенесен в в обработчики mouseup и touchend эвентов.
=> fix(swipeable): fixed swipeable delta calculation

CONTRIBUTION.md
Обновил ссылку на формат коммитов.
Сегодня в проекте ангуляра этот кусок доки переехал в другой файл.
=> chore(*): updated git commit format link

src/input/input.css
Исправление обрезания аддонов в IE11.
=> fix(input): avoid overflow cutting of addons in ie11

src/lib/scroll-to-test.js
Исправление проблем с тестами на iOS Safari 10+.
Незадействованное увеличение ширины экрана вкупе с промисом в каждом тесте на `scroll-to` выстреливало пачку ивентов на изменение матчинга в `<Mq />`:
https://github.com/alfa-laboratory/arui-feather/blob/master/src/mq/mq.jsx#L41
Пачка ивентов триггерила массу `setState` дальше по дереву, в итоге можно было словить например здесь проблемы с множественными изменениями state и демонтирования компонента:
https://github.com/alfa-laboratory/arui-feather/blob/master/src/select/select.jsx#L263
Что вело к разного рода ошибкам, например:
```
link
✖ should call `onClick` callback after link was clicked
Mobile Safari 11.0.0 (iOS 11.1.0)
NotFoundError (DOM Exception 8): The object can not be found here. …
```
=> test(*): fix troubles between promise-based scroll-to tests & mq events

src/intl-phone-input/intl-phone-input.css, src/intl-phone-input/intl-phone-input.jsx
Необходимо для использования `width: 'available'` например. Ну и минус одна ненужная нода в DOM.
=> fix(intl-phone-input): use input as root node

src/link/link-test.jsx, src/link/link.jsx
Исправил уязвимость связанную с target='_blank';
https://mathiasbynens.github.io/rel-noopener/
Вообще по хорошему передавать кастомные пропсы пользователей дальше в компонент. Вдруг кому - то нужно будет атрибут aria или другие атрибуты, но как - то с первого раза у меня не получилось это сделать, чуть позже предложу второй PR
=> fix(link): fix security bug wich work via target='_blank'

.travis.yml
`$ yarn install`
```
warning You are using Node "7.4.0" which is not supported and may encounter bugs or unexpected behavior. Yarn supports the following semver range: "^4.8.0 || ^5.7.0 || ^6.2.2 || >=8.0.0"
```
Текущая LTS в Node: 8.9.3
Последняя предустановленная на Travis: 8.9.1
=> chore(ci): update nodejs on travis to 8.9.1

src/intl-phone-input/intl-phone-input-test.jsx, src/intl-phone-input/intl-phone-input.jsx
Оптимизация первой загрузки для компонента intl-phone-input
На данный момент если intl-phone-input расположен на первой загружаемой странице, то все флаги стран и утилита грузится сразу. Это не есть хорошо, так как увеличивается время первоначальной загрузки страницы. Решением было перенести загрузку флагов и утилиты на момент фокуса на селекте с флагами.
=> fix(intl-phone-input): optimizing intl-phone-input component

src/button/button.css, src/spin/spin.css
Фикс выравнивания иконки в кнопки
Иконка выравнивалась по верхнему краю на iOS 10.
=> fix(button): fix icon alignment in button

src/calendar/calendar.jsx
Откатка изменений после https://github.com/alfa-laboratory/arui-feather/pull/425
`Number.isFinite` нет в IE11.
Если есть идеи как быстро сделать лучше — велкам.
=> fix(calendar): fix Number.isFinite troubles in ie11

README_MOBILE.md, src/calendar-input/calendar-input-test.jsx, src/calendar-input/calendar-input.jsx
Добавить возможность задать аттрибуты max/min для нативного календаря.
При использовании нативного календаря хотелось бы проставлять аттрибуты max/min.
=> feat(calendar-input): add max-min attribute for native calendar

src/input/input.css, src/textarea/textarea.css
Оверрайд для предотвращения подобного:
=> feat(*): override default browser border-radius on controls

src/popup-container-provider/popup-container-provider-test.jsx, src/popup-container-provider/popup-container-provider.jsx
Добавил метод getNode в popup-container-provider
Необходим для сохранения обратной совместимости с React v15 в редких случаях с модалками
=> feat(popup-container-provider): getNode method

src/input/input.jsx
Убрал выставление value в стейт для случая, если value передаётся с пропсами. Зачем надо? Об этом далее. (Воспроизводится в 16 реакте, при использовании редакс-форм)
В рендере если инпут привязан к валью в пропсах, то он игнорирует значение в стейте. 
При этом если мы делаем setState, в пропсы ещё не обновились, то у нас берётся предыдущее значение value из пропсов
let value = this.props.value !== undefined
? this.props.value
: this.state.value;
и апдейтится value инпута на старое значение. 
Потом апдейтятся пропсы и компонент снова перерисовывается уже с новым значением, и каретка улетает в конец инпута.
Порочный воркфлоу такой:
Поехал changeValue -> setState -> (тут же рендер с предыдущим props.value) -> dispatch new props -> (снова рендер, но уже с новыми props.value)
=> fix(input): no need to set state if input value is controlled by input

package-lock.json, package.json
Удаление явно указанной версии `acorn` для работоспособности одной из предыдущих версий `react-syleguidist`. С последними версиями всё хорошо.
=> refactor(*): remove acorn low version in deps

src/intl-phone-input/intl-phone-input-test.jsx, src/intl-phone-input/intl-phone-input.jsx
Делаем проверку на длину введенного номера только для российских номеров.
Так как с иностранными номерами могут быть нюансы, то ограничивать их на ввод по длине не будем.
=> fix(intl-phone-input): remove restriction of phone number length

src/calendar/calendar.css
Изменил стили кнопки навигации календаря
Сейчас при переходе на последнюю страницу календаря, кнопке ставится стиль `visibility: hidden`. По этому происходит блюр и в случае `CalendarInput` popup календарь скрывается.
Скрины проблемы:
=> fix(calendar): fix calendar blur on last month page

src/calendar/calendar.jsx
Исправлен баг календаря при отображении диапазона дат
Значение записывалось в selectedFrom вместо selectedTo, поэтому даты внутри диапазона не окрашивались.
=> fix(calendar): Fixed period selection in calendar

src/menu/menu.jsx
Изменение дефолтного значения переменной highlightedItem с null на undefined
Ломается повторный highlight в inputAutocomplete (можно наблюдать на нашей странице со стайлгайдом, в разделе "Автокомплит с автозакрытием после выбора". Один раз что-то выбрали, второй раз на hover компоненты не подсвечиваются и навигация стрелочками клавиатуры не работает). Проблема наблюдается на всех(!) проектах, которые используют инпут-автокомплит(например на рублёвке). 
Первые два примера в стайлгайдисте не ломаются, потому что сам компонент не перерендеривается и componentWillReceiveProps в менюхе повторно не срабатывает и не выставляет highlightedItem в null
Поскольку в компоненте Menu везде стоят такие проверки:
let highlightedItem = this.props.highlightedItem === undefined
? this.state.highlightedItem …
=> fix(menu): input-autocomplete highlight fix

src/calendar-input/calendar-input.css
Синий текст внутри `CalendarInput` на iPhone
Сейчас на iPhone внутри `CalanderInput`(без фоллбэка на нативный контрол) выводится текст синего цвета
=> fix(calendar-input.css): fix input text color on ios

src/select/select.css, src/select/select.jsx, src/select/select_theme_alfa-on-color.css, src/select/select_theme_alfa-on-white.css
Цвет для placeholder, изменение display для правильного сокращения строки
Если значение в select длинное (или их несколько), то строка не сокращалась как в инпуте, а залазила на стрелочку. Изменения display: flex; на display: inline-block; исправляет этот баг.
Цвет плейсхолдера в селекте не соответствовал плейсхолдерам других компонентов (например инпут обычный). Добавил вывод плейсхолдера через <span> с классом и соответствующими стилями.
=> fix(select): add placeholder color and right display for text

src/input/input.css, src/input/input_theme_alfa-on-color.css, src/input/input_theme_alfa-on-white.css
На андроидах 4.1–4.3 плейсхолдер накладывался на лейбл (до фокуса).
=> fix(input): placeholder visibility on android < 4.4

src/button/button.css
В Safari на iOS 10 у кнопки с width='available' текст выравнивался не по центру, а по левому краю:
=> fix(button): text align in full width button

src/mq/decorator.d.ts
Фикс типов для mq-decorator
Текущие типы просто не компилятся.
=> fix(mq): correct d.ts for mq-decorator

package-lock.json, src/input-autocomplete/input-autocomplete-test.jsx, src/input-autocomplete/input-autocomplete.jsx
Попап со списком элементов вставлять в DOM только если input активен
При большом количестве таких элементов на странице рендер выполняется очень долго, порядка секунды.
Идея в том, что бы рендерить список только если input получил фокус.
Для того, что бы не ломать обратную совместимость добавлен флаг, включающий лайт режим.
=> feat(autocomplete): insert popup after focus

src/menu-item/menu-item.jsx, src/menu-item/menu-item.test.jsx
There is no other way to set theme to inner link. And now it's
definitely not expected.
Добавлен проброс темы из MenuItem во внутренние элементы.
Они делают поведение MenuItem и темы более ожидаемое, и сейчас нету другого способа, чтобы поменять тему у внутренних элементов.
=> fix(menu-item): add sending theme prop to inner link or dropdown element

src/lib/currency-codes.js
Добавил символ швейцарского франка в утилиту currency-codes
Изменения необходимы так как швейцарский франк является одной из восьми основных валют для Альфа Private, и в компоненте Amount отсутствует символ, а используется просто код `CHF`. Добавленный символ совпадает с французским франком, но это нормальная ситуация, потому что символ франка ₣ подходит вообще для любых франков.
=> feat(utils/currency-codes): add symbol accroding CHF currency code

.travis.yml
Обновление https://design.alfabank.ru/ теперь происходит только в том случае, если целевой веткой является `master`, пройдены тесты и `TRAVIS_PULL_REQUEST` равен `false`.
=> chore(*): travis config update

src/button/button.jsx
Было пропущено свойство "key" в компоненте кнопки, что приводит к выводу warning в консоль.
=> fix(button): add skipped "key" property

src/input/input.jsx, src/input/input.test.jsx
Не даем прокручивать контент инпута, если он без фокуса
#708
=> fix(input): disable horizontal scroll for a inputs

src/performance.d.ts
performance.d.ts
(5,37): error TS2371: A parameter initializer is only allowed in a function or constructor implementation.
=> fix(types): performance typing param init error

src/input/input.css
В продакшн-сборке (arui-presets) в IE11 у инпута плейсхолдер накладывался на лейбл.
=> fix(input): input with label and placeholder in ie11

src/vars/color-theme_alfa-on-white.css
Добавлен цвет dark_indigo_05 из дизайн-гайда
В проектах дизайнеры часто используют данный цвет фона для элементов, ссылаясь на design-guide.
=> feat(colors): add gray new background color with transparancy of .05

src/calendar-input/calendar-input.jsx, src/calendar-input/calendar-input.test.jsx
Прокидываем autocomplete в компонент Input внутри CalendarInput,
иначе попап с автокомплитом перекрывает календарь.
=> feat(CalendarInput): add autocomplete prop

package.json, src/popup/popup.jsx, src/radio/__snapshots__/radio.test.jsx.snap, src/radio/radio.jsx, yarn.lock
На сервере отрендерилось одно, на клиенте другое. При вызове ReactDOM.hydrate, реакту это не нравилось. Поэтому костыль canUseDOM из exenv был заменён на setState.
Более подробно про hydrate и setState способ можно узнать из [офф. документации](https://github.com/reactjs/reactjs.org/blob/25df15b83edb903862504457b107682faf4f676b/content/docs/reference-react-dom.md#hydrate-hydrate).
=> Фикс рендер popup'a для SSR и react@16^

src/amount/amount.jsx, src/lib/format-amount.js, src/lib/format-amount.test.jsx
Утилитарные функции `amount` должны лежать отдельно
1. Это позволяет использовать их независимо от самого компонента, для форматирования сумм
2. Проблема, которая решается сейчас -> Отображение `checkedText` в `Select`
=> feat(amount): move util functions to lib, add function to generate formatted amount in string

src/select/__snapshots__/select.test.jsx.snap, src/select/select.jsx
При большом количестве элементов начинаются проблемы с производительностью из-за ResizeSensor, убираем его до открытия Popup.
=> feat(select): ResizeSensor on focus only

src/sidebar/sidebar.jsx
Фикс бага со скроллом из-за выполнения кода для мобильной версии на десктопе (скролл `window` перезатирался сохраненным скроллом в сайдбаре)
Отделил логику `setCurrentPosition` от `setBodyClass `.
=> fix sidebar scroll position bug

package-lock.json, src/input-autocomplete/input-autocomplete.jsx, src/input/input.jsx, src/input/input.test.jsx
Разрешаем пробрасывать строковое значение в проп `automplete` у инпута.
Не смотря на то, что в стандартах указано что возможны лишь два значения - `on` и `off` но браузеры уже давно смотрят на другие значения, например `email` включит автофил для почты, а `new-password` вырубит автозаполнение полностью
=> feat(input): allow to pass string autocomplete prop value

src/calendar-input/calendar-input.test.jsx
Тесты для `mobileMode` у `<CalendarInput />`
Исправляет issue #621
=> test(CalendarInput): add tests for mobileMode prop

src/amount/amount.test.jsx, src/lib/format-amount.js
Теперь в компонент `Amount` можно передавать `0` в свойстве `amount.currency.minority`  и это не приведёт к ошибке.
Пользователь компонента может по ошибке передать ноль в minority. Это приводит к тому, что компонент перестаёт отображаться.
Проверить проблему сейчас можно здесь https://design.alfabank.ru/components/amount
=> fix(amount component): now does not explode if passing minority 0

src/input/input.jsx
Исправляет проблему с переходами между группой инпутов с помощью кнопки TAB.
На данный момент для кнопки очистки нет никаких A11Y вещей и соответственно переход на неё через TAB визуально не меняет отображение этой кнопки, что вводит в заблуждение пользователей.
При этом для пользователя важнее перейти на другое поле, а не очистить текущее поле. Но в рамках больших форм прописывать tabIndex для каждого инпута — это боль.
В дальнейшем можно будет сделать что-то типа *clearTabIndex*, чтобы иметь возможность управлять её tabIndex-ом.
=> fix(input): add tabIndex for clear button

src/vars.css
Negative analogues for all current gaps have been added.
Often developers had to use records like `margin: calc(-1 * var(--gap-4xs));`, which are difficult to read and looks ugly in general. Some developers avoid using gaps in such cases at all. After this changes we can simply type `margin: var(--gap-4xl-neg);`
=> feat(vars): add negative gaps

src/input/input_theme_alfa-on-color.css, src/input/input_theme_alfa-on-white.css
Фикс цвета каретки в input.
В поле ввода, после выбора одного из предложенных элементов (имеются ввиду те значения, которые пользователь уже раньше когда-то вбивал и они сохранились в браузере) каретка становится черного цвета (это заметно только в темной теме) и совершенно незаметна.
Этот маленький фикс исправляет данную проблему.
=> fix(input): fix caret color

src/button/button.jsx
Add `data-test-id` property to button component for autotests
In most cases autotest suits uses test locators to perform desired actions with located elements. `id` property is not always suitable for this purpose as it should be unique on page, and this is not always logically achievable.
`className` property is not suitable as well as it can be changed in future if styles are modified or project structure partially changed. Property `data-test-id` is usually used to make distinct way to locate DOM element.
____________________
В большинстве случаев средства автоматического тестирования используют тестовые локаторы для выполнения необходимых действий над найденными элементами. Свойство `id` не всегда подходит для этих целей, так как должно быть уникальным на странице, а это не всегда …
=> feat(button): add data-test-id property to button component

src/money-input/README.md, src/money-input/money-input.css
> После обновления arui-feather до 14.0.0 появился баг с компонентом money-input — при наличии label съезжает символ валюты.
Демка с фиксом: https://deploy-preview-838--arui-feather.netlify.com/#!/MoneyInput
=> fix(money-input): label and currency style fix

src/input/input.css, src/input/input_theme_alfa-on-color.css, src/input/input_theme_alfa-on-white.css
Решение проблемы с некорректными стилями заблокированного Input (#781)
Проблема наблюдалась
- при автоматической блокировке поля (передается пропс disabled) при достижении определенных условий. В этом случае оставалась лишняя нижняя граница.
- при выборе варианта из нативного автозаполнения браузера. В этом случае к тексту не применялся стиль заблокированного Input.
=> fix(input): incorrect disabled input styles (#781)

src/masked-input/masked-input.jsx, src/masked-input/masked-input.test.jsx
- Добавлены тесты, которые проверяют позиционирование каретки в проблемных кейсах.
- Исправлено позиционирование каретки в случаях, когда, после изменения значения MaskedInput, слева от каретки меняется количество не редактируемых символов.
В компоненте MoneyInput, который внутри себя использует компонент MaskedInput, в процессе редактирования суммы, каретка "перескакивала" на соседние цифры.
- если слева от каретки появлялся разделитель (не редактируемый символ), то каретка перескакивала на один символ влево.
- если слева от каретки исчезал разделитель (не редактируемый символ), то каретка перескакивала на один символ вправо.
=> fix(masked-input): caret position if mask changes

src/tag-button/tag-button.css
TabButton (и, как следствие, CheckBox/Radio type = button checked) с параметром checked={true} не "подсвечивал" при фокусе.
Теперь кнопка с checked={true} меняет цвет, когда получает фокус.
=> fix(tab-button): checked with focused styles

src/calendar/calendar.jsx
Исправлено поведение CalendarInput, когда, после выбора месяца или года, календарь не закрывался, при click outside.
=> fix(calendar): focus when select month or year

src/input-autocomplete/input-autocomplete.jsx
**Add max height for popup content in InputAutocomplete**
This opportunity is optional and allows to limit height of content.
=> feat(input-autocomplete): add max height for popup content

src/input-autocomplete/input-autocomplete.jsx, src/popup/popup.css, src/popup/popup.jsx
Добавлено ограничение высоты popup при заданной максимальной высоте (maxHeight)
=> feat(popup): add max height and scroll

.eslintrc.js, .eslintrc.styleguide.js, package-lock.json, package.json
Preparation for migrate to latest ReactJS version https://github.com/alfa-laboratory/arui-feather/issues/881
=> feat(eslint) migration from arui-presets/eslint to arui-presets-lint/eslint

src/select/select.css
Исправление ширины для select с классом .select_view_filled
Если использовать select с классом .select_view_filled, то ширина выставляется на 100+% когда transform по X нету. Соответственно блок селекта занимает больше места по оси X что приводит к появлению ненужного скролла
=> fix(select): style for .select_view_filled

src/tab-item/__snapshots__/tab-item.test.jsx.snap, src/tab-item/tab-item.jsx
Изменен дефолтный `view` prop с несуществующего значения `dark` на `default` в компоненте `TabItem`, чтобы пофиксить warning.
По дефолту prop `view` ставится в `dark`. Это вызывает warning у потребителя компонента:
> Invalid prop `view` of value `dark` supplied to `TabItem`, expected one of ["default", "blue"]
PropTypes для компонента `TabItem` определены в `Link`, от которого он наследуется. В указанных значениях `view` у `Link` нет значения `dark`.
=> fix(tab-item): change default view prop to 'default' in TabItem

src/input/input.jsx, src/input/input.test.jsx
Применить в атрибуте неиспользуемый `data-test-id` prop в элементе input.
В этом [коммите ](https://github.com/alfa-laboratory/arui-feather/commit/599bcf42e4347045b82fc824a571df9d8ce9a947#diff-a103783815939099d5b5bd3c9506451f) добавили атрибут `data-test-id` для `input` и других компонентов.  
Однако в следующем [коммите ](https://github.com/alfa-laboratory/arui-feather/commit/e5539ffdda99f8c603d66a58a798d2c87231869e#diff-a103783815939099d5b5bd3c9506451f) применение атрибута `data-test-id` в компоненте `input` удалили, но сам prop `data-test-id` оставили.
Кажется, нужно либо удалить его с концами, либо вернуть его использование обратно. Я вернул изменения обратно из вышеупомянутого коммита.
=> fix(input): fix missing data-test-id attribute in input

styleguide.config.js
Фиксим описание пропсов на демке для тайпскрипта
=> fix(*): hotfix typescript demo docs

src/lib/window.test.tsx, src/lib/window.ts, yarn.lock
https://github.com/alfa-laboratory/arui-feather/issues/1021
Пришлось немного переписать тесты.
Апдейт yarn.lock, потому что `cn-decorator` куда-то потерялся
=> chore(window): window to typescript

src/attach/attach.test.tsx, src/attach/attach.tsx
Возможность обрезать имя файла, если оно слишком длинное.
Появилась необходимость обрезать имя файла, т.к. оно может слишком сильно растягивать верстку.
=> feat(attach): truncate filename

src/lib/prop-types.ts
Closes #1052
Валидаторы из prop-types.js переведены на TS
Больше типизации с Typescript
=> chore(*): migrate prop-types validators to TS

src/button/button.tsx, src/collapse/collapse.tsx, src/dropdown/dropdown.tsx, src/form-field/form-field.tsx, src/form/form.tsx, src/heading/heading.tsx, src/input-group/input-group.tsx, src/label/label.tsx, src/link/link.tsx, src/menu-item/menu-item.tsx, src/notification/notification.tsx, src/paragraph/paragraph.tsx, src/popup-container-provider/popup-container-provider.tsx, src/popup/popup.tsx, src/radio-group/radio-group.tsx, src/sidebar/sidebar.tsx
children тип заменил на React.ReactNode и проблема ушла
А вообще https://github.com/alfa-laboratory/library-utils/blob/master/typings/stringify-component-definition.js#L88
Вот тут все происходит. В проптайпах было явно вот так написано
children: Type.arrayOf(Type.node),
children: Type.oneOfType([Type.arrayOf(Type.node), Type.node]),
=> fix(*): use React.ReactNode

src/checkbox-group/__snapshots__/checkbox-group.test.tsx.snap, src/checkbox-group/checkbox-group.test.tsx, src/checkbox-group/checkbox-group.tsx, src/radio-group/__snapshots__/radio-group.test.tsx.snap, src/radio-group/radio-group.test.tsx, src/radio-group/radio-group.tsx
Добавляет проверку для дочерних компонентов
Иногда есть необходимость регулировать рендер детей через `&&`.
Например `{ isOneEl && <Radio />}`.
До изменений все падоло с ошибками по типу `Cannot read property 'error' of undefined`.
Ошибка происходила `error: radio.props.error === undefined`.
После добавления этой проверки, такого не происходит
=> fix(radio-group): adds 'isValidElement' check for children

src/vars/font.css
В последнем Chrome 81 на маке есть баг, ломающий наши шрифты:
https://www.bram.us/2020/04/09/chrome-vs-blinkmacsystemfont-when-bold-is-not-bold/
В этом реквесте — временное решение. Шрифт в Chrome поменяется, но болд вернётся.
Chrome с фиксом ждать до середины мая (если не ускорят).
=> fix(*): temporary fix for chrome font bug

src/textarea/textarea.css
https://github.com/alfa-laboratory/arui-feather/issues/1118
Данная проблема возникает при сочетании `view="filled"` и `maxRows`.
Из-за особенностей вертки - контент во время скрола наезжает на лейбл. 
Перенес заливку из `textarea.textarea__control` в родительский контейнер `.textarea__inner` и добавил дополнительный паддинг сверху при фокусе или если есть введенное значение.
=> fix(textarea): fixed height label overlapping on view=filled

src/input/README.md, src/input/input.tsx
Текущее описание свойства`useWhitespacesInMask` - это перевод его названия, и его можно очень широко интерпретировать. Применяя это свойство, я ожидал другого поведения.  
Стало непонятно, что делает это свойство и в каких случаях оно оказывает влияние.  
Почитав код и поговорив с человеком, использующим свойство, пришел к такому описанию.
=> docs(input): update useWhitespacesInMask description

src/menu/menu.css
top для .menu-item_checked:before вычисляется динамически
Если top будет константой, то смотрится криво.
=> fix(menu): top in .menu-item_checked:before

src/masked-input/__snapshots__/masked-input.test.tsx.snap, src/masked-input/masked-input.tsx
- Убрал неявную установку атрибута maxLength в `<MaskedInput/>`
`inputmask-core` не даст ввести больше символов, чем определено маской, поэтому специально устанавливать данный атрибут не нужно.
Но если очень хочется, то это можно сделать явно, через пропс `maxLength` 🤷‍♂️
https://github.com/alfa-laboratory/arui-feather/issues/1141
=> fix(masked-input): remove implicit maxLength setting

src/vars/font.css
После фикса бага в хроме на маке возвращаем font-family, но возвращаем не устаревший `BlinkMacSystemFont`, а `system-ui`
=> fix(*): revert font-family after fix in chrome

package.json
Понижение версии react-styleguidist с 9.1.16 до 9.1.5
Решаемая проблема: https://github.com/alfa-laboratory/arui-feather/issues/1102
Проблема заключается в том, что вместо ThemedComponent подтягивается Component
По результатам ресерча - по приоритетам в начале идет именованный экспорт, затем - экспорт по умолчанию
следовательно, если есть, к примеру
export { default } from './button';
export * from './button';
при импорте Button будет импортирован именно Button, а не экспортируемый по умолчанию ThemedButton
https://github.com/styleguidist/react-styleguidist/issues/1413
такое поведение начинается с версии 9.1.6
Возможное решение - переход на версию 9.1.5
=> chore(*): downgrade react-styleguidist

src/money-input/money-input.test.tsx, src/money-input/money-input.tsx
Фиксит отображение значка валюты
Значок валюты некорректно отображается при использовании плейсхолдера и длинных значений.
Связанные issues: https://github.com/alfa-laboratory/arui-feather/issues/1159 и https://github.com/alfa-laboratory/arui-feather/issues/1164
=> fix(money-input): fix currency overlapping

src/input-autocomplete/__snapshots__/input-autocomplete.test.tsx.snap, src/input/__snapshots__/input.test.tsx.snap, src/input/input.css, src/input/input.tsx, src/intl-phone-input/intl-phone-input.css, src/money-input/money-input.css
Исправлен баг с позиционированием лейбла при наличии аддонов.
https://github.com/alfa-laboratory/arui-feather/issues/1169
- Обернул инпут в контейнер
- Перенес в этот контейнер рендер лейбла, чтобы его позиция всегда совпадала с позицией инпута, не смотря на наличие аддонов и их размер.
- Исправил оверрайды стилей в MoneyInput и IntlPhoneInput
=> fix(input): fix label position when input has addons

src/calendar-input/calendar-input.tsx
Передача `resetError` через `CalendarInput`. 
Компонент `CalendarInput` использует `Input` с некоторыми заданными пропсами, но не передает `resetError` если мы его зададим в `CalendarInput`. Из-за этого ошибка на инпуте ресетится при фокусе и этим невозможно никак управлять. 
Проблема связана с issues, но так как они не имеют пока решения, надо как-то управлять компонентом: 
https://github.com/alfa-laboratory/arui-feather/issues/1119
https://github.com/alfa-laboratory/arui-feather/issues/1120
=> feat(calendar-input): pass resetError through Calendar to Input

tools/icon/icon.test.tsx.hbs, tools/icon/icon.tsx.hbs, tools/icon/index.ts.hbs
Обновил темплейты для build:icons npm-команды
Захотелось научиться обновлять иконки - нашел команду build:icons, которая, как я понимаю, должна для этого использоваться. Она сгенерировала более 900 файлов - все иконки.
Кажется, hbs-шаблоны для команды устарели, пути по-моему там неверные.
После моих изменений запуск команды не генерирует кучу новых файлов.
=> fix(*): fix hbs-templates for build:icons command

src/input/input.css
=> fix(input): input wrapper take all remaining from addons space

package.json
Правим работу semantic-release
В отличии от yarn, npm не умеет запускать бинарники через `npm run ...` если они явно не прописаны в package.json
=> chore(package): allow to run semantic release by npm

.github/workflows/tests.yml
Меняет план для запуска тестов
В старой версии при необновленном package-lock сборка не падала на тестах, но валилась на релизе. 
С этими изменениями будет бадать на тестах.
=> feat(*): change 'npm i' on 'npm ci'

package-lock.json, package.json, src/calendar/__snapshots__/calendar.test.tsx.snap, src/calendar/calendar.test.tsx, src/calendar/calendar.tsx
Добавил флаг ignoreTimezones, при включении игнорируется время для дат offDays и eventDays, для корректного отображения у пользователей из разных таймзон.
Проблема описана в issue #1232
=> fix(calendar): show offDays and eventDays for different timezones

src/money-input/money-input.tsx
Добавил проверку на лишние нули в начале значения в MoneyInput. Если первая цифра ноль, то следующим символом может быть только десятичный разделитель. 
Fixes #1186
=> fix(money-input): add check for leading zeros

src/calendar/calendar.tsx
Добавлен reverseYearsOrder параметр для изменения последовательности лет в селекте
По-умолчанию года в селекте отображаются по убыванию.
Есть кейс когда нужно отображать года по возрастанию
=> feat(calendar): add reverseYearsOrder prop to change order of years
